name: amend

on:
  issue_comment:
    types: [created]

jobs:
  amend:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/amend')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: amend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh checkout "${{ github.event.pull_request.html_url }}"
            git config --global user.name '${{ github.actor }}'
            git config --global user.email 'opensource@payex.com'
            git commit --amend --no-edit
            git push --force
