name: Release PR

on:
  push:
    branches:
      - release/*

jobs:
  release-develop-pr:
    runs-on: ubuntu-latest
    steps:
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: develop
          pr_title: "Release ${{ github.ref }} (develop)"
          pr_body: ":crown: *An automated PR*"
          pr_label: "release"
          pr_milestone: "${{ github.ref }}"
          pr_draft: true
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

  release-master-pr:
    runs-on: ubuntu-latest
    steps:
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: master
          pr_title: "Release ${{ github.ref }} (master)"
          pr_body: ":crown: *An automated PR*"
          pr_label: "release"
          pr_milestone: "${{ github.ref }}"
          pr_draft: true
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
