name: release

on:
  push:
    branches:
      - release/*

jobs:
  release-name:
    outputs:
      name: ${{ steps.name.outputs.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Create release name
        id: name
        env:
          REF: ${{ github.ref }}
        run: |
          name="${REF#refs/heads/release/}"
          echo "Name: $name"
          echo "::set-output name=name::$name"

  release-develop-pr:
    runs-on: ubuntu-latest
    needs: release-name
    steps:
      - uses: actions/checkout@v2
      - uses: repo-sync/pull-request@v2
        with:
          destination_branch: develop
          pr_title: Release ${{ needs.release-name.outputs.name }} (develop)
          pr_body: "## Release ${{ needs.release-name.outputs.name }} (develop)\n:crown: *An automated PR*"
          pr_label: release
          pr_draft: true
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

  release-main-pr:
    runs-on: ubuntu-latest
    needs: release-name
    steps:
      - uses: actions/checkout@v2
      - uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          pr_title: Release ${{ needs.release-name.outputs.name }} (main)
          pr_body: "## Release ${{ needs.release-name.outputs.name }} (main)\n:crown: *An automated PR*"
          pr_label: release
          pr_draft: true
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
